<a href="https://colab.research.google.com/github/trixmcc/LinearAlgebra1T-2021-2022/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
### Laboratory 4 : Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

# I. Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# II. Methodology

### For Task 1:
<center><img src = "https://i.ibb.co/X3DtSxr/cruz-flowchart-task1.jpg"></center>

We start the program with an input matrix and evaluate it in few conditions to determine its type.

In the 1st condition: if the matrix size is larger than 0, then the matrix has elements in it and would proceed to the second condition. If it is 0, then the matrix has no elements. It will print null instead and finish the program.

In the 2nd condition: after it was proven that the matrix has elements, we will evaluate if is square, where the number of rows are the same with the number of columns. If it is, "True" will be printed. Otherwise, it will print "False". Whether the output is True or False, the program will continue to the next condition.

In the 3rd condition: the matrix will be evaluated if it is zeros, where all elements are zeros. If it is, "True" will be printed. Otherwise, "False". Regardless of the output, the program will continue to the next condition.

In the 4th: the matrix will be evaluated if it is ones, where all elements are one. If it is, "True" will be printed. Otherwise, "False". Regardless of the output, the program will continue to the next condition.

In the 5th and last condition: the matrix will be evaluated if it is identity, where the element has a diagonal of ones surrounded with 0. If it is, "True" will be printed. Otherwise, "False". Afterwards, the program will end.

To summarize, this program will print outputs that can either be:
*   null for size
*   true/false for square, true/false for zeros, true/false for ones and true/false for identity.



### For Task 2:
<center><img src = "https://i.ibb.co/QpQnzP3/cruz-flowchart-task2.jpg"></center>

We start the program with input matrices and evaluate whether they are viable for opertaions. There are two computations in which a matrix expression may be able to do, and either of them will be performed depending on the iput expression.
1. If a number is added/subtracted/multiplied/divided to a matrix of any shape, the operation will be performed and will print result.
2. If a matrix is element-wise operated to another matrix, it will undergo evaluation through a condition. If both matrices have the same shape, they can perform the operation and will print result. Otherwise, execution will be unsuccessful and return Value Error.

Afterwards, the program will end. The possible outputs would be: printed result of the operation or the error.

# III. Discussion<sup>[1][2][3][4][5]</sup>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

NumPy - A library that serves as the foundation for scientific computing in Python. It offers a set of tools and strategies for solving mathematical models of problems in Science and Engineering on a computer. A high-performance multidimensional array object, which is a powerful data structure for efficient computation of arrays and matrices, is one of these tools. A large number of high-level mathematical functions act on these matrices and arrays to work with them. [1]

Pyplot - matplotlib.pyplot is a set of routines that allows it to function similarly to MATLAB. Each pyplot function alters a figure in some way, such as constructing a figure, a plotting area in a figure, charting specified lines in a plotting area, and so on. Throughout function calls, matplotlib.pyplot keeps track of several states, current figure and plotting area, as well as guide plotting actions to the current axes. [2]

SciPy - based on the ATLAS LAPACK and BLAS libraries, which have been improved. Its linear algebra capabilities are quite quick. These linear algebra techniques all require an object that can be transformed into a two-dimensional array. These algorithms produce a two-dimensional array as well. [3]

## Matrices

A matrix is a row-by-column array of integers, symbols, or expressions. Rows and columns, respectively, refer to the horizontal and vertical lines of elements in a matrix. The number of rows and columns that make up a matrix determines its size. An $i$ x $j$ matrix or $i$ -by- $j$ matrix is a matrix with $i$ rows and $j$ columns, and where $i$ and $j$ are dimentsions. [4]

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

Generally, the elements of a matrix can be represented as this:

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

### Declaring Matrices

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [2]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [3]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [4]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [5]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [6]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



### Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

#### According to shape

##### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [7]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [8]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



##### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [9]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [10]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



#### According to element values

##### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [11]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [12]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


##### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [13]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [14]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [15]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [16]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]


False

##### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [19]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

##### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [20]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Matrix Algebra

Matrix Algebra is a branch of mathematics that deals with vector spaces in multiple dimensions. Matrix algebra was invented as a result of the presence of n-dimensional planes in our coordinate system.

The operations, including addition, subtraction, multiplication, and division, are covered in Matrix Algebra. [5]

### Addition

In [21]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [22]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [23]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [24]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [25]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [26]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [27]:
A@B

ValueError: ignored

In [28]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [29]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

# IV. RESULTS

### Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [30]:
theta = np.array([[5, 3, -1]])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2
Is Square: False



2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [31]:
A = np.array([
              [1, 2, 1],
              [0, 4,-1],
              [0, 0, 10]
])
describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



3. Given the matrix below, express it as a linear combination in a markdown.

In [32]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
G = \left\{
    \begin{array}\
        x + 7x_{2}+8x_{3}\\ 
        2x + 2x_{2}+2x_{3}\\
        4x+6x_{2}+7x_{3}
    \end{array}
\right. \\
$$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [33]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [34]:
## Function area

def mat_desc(matrix):

  # Determining Empty Matrix
  if matrix.size > 0:
    rows = matrix.shape[0];  
    cols = matrix.shape[1];

    # Determining Square Matrix
    is_square = True if rows == cols else False

    # Determining Zero Matrix
    is_zeros = True if np.all(matrix == 0) else False
        
    # Determining Ones Matrix
    is_ones = True if np.all(matrix == 1) else False

    # Determining Identity Matrix
    is_identity = True
    for i in range(rows):
        for j in range(cols) :
            if ((i != j) and (matrix[i][j] != 0)):
                is_identity = False
            if ((i == j) and (matrix[i][j] != 1)):
                is_identity = False

    print(f"Matrix: \n{matrix}\n\nShape: {matrix.shape}\nRank: {matrix.ndim}\nIs Square: {is_square}\nIs Zeros: {is_zeros}\nIs Ones: {is_ones}\nIs Identity: {is_identity}")
  
  else:
    print(f"The matrix is Null.")

In [35]:
## Matrix declarations

Sample1A = np.array([])

Sample2A = np.array([
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]
])

Sample3A = np.zeros((5, 3))

Sample4A = np.ones((4, 4))

Sample5A = np.eye(5)

In [36]:
## Test Areas

print("--Sample1A--")
mat_desc(Sample1A)
print(f"\n")

print("--Sample2A--")
mat_desc(Sample2A)
print(f"\n")

print("--Sample3A--")
mat_desc(Sample3A)
print(f"\n")

print("--Sample4A--")
mat_desc(Sample4A)
print(f"\n")

print("--Sample5A--")
mat_desc(Sample5A)

--Sample1A--
The matrix is Null.


--Sample2A--
Matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3)
Rank: 2
Is Square: True
Is Zeros: False
Is Ones: False
Is Identity: False


--Sample3A--
Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape: (5, 3)
Rank: 2
Is Square: False
Is Zeros: True
Is Ones: False
Is Identity: False


--Sample4A--
Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Shape: (4, 4)
Rank: 2
Is Square: True
Is Zeros: False
Is Ones: True
Is Identity: False


--Sample5A--
Matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Shape: (5, 5)
Rank: 2
Is Square: True
Is Zeros: False
Is Ones: False
Is Identity: True


### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [37]:
def mat_operations(matrix):
  print(matrix);


In [38]:
Sample1B = np.array([
                     [4, 6, 1, 7, 3],
                     [2, 5, 2, 6, 7],
                     [2, 8, 2, 6, 6],
                     [9, 5, 1, 7, 2]
                    ])

Sample2B = np.array([
                     [1, 6, 3, 5, 2],
                     [5, 7, 1, 7, 3],
                     [6, 2, 8, 5, 5],
                     [3, 9, 2, 1, 0]
])

Sample3B = np.array([
                     [7, 4, 2, 6],
                     [9, 6, 2, 7],
                     [3, 6, 1, 5]
])

Sample4B = np.array([
                      [9, 4, 2, 8],
                      [2, 6, 3, 7],
                      [5, 1, 0, 3]
])

Sample5B = np.array([
                     [8, 7, 2, 8],
                     [1, 0, 2, 7],
                     [0, 1, 4, 6]
])



In [39]:
mat_operations(Sample2B + Sample1B)

[[ 5 12  4 12  5]
 [ 7 12  3 13 10]
 [ 8 10 10 11 11]
 [12 14  3  8  2]]


In [40]:
mat_operations(Sample1B - 2)

[[ 2  4 -1  5  1]
 [ 0  3  0  4  5]
 [ 0  6  0  4  4]
 [ 7  3 -1  5  0]]


In [41]:
mat_operations(Sample1B + Sample5B)

ValueError: ignored

In [42]:
mat_operations(Sample3B * Sample5B)

[[56 28  4 48]
 [ 9  0  4 49]
 [ 0  6  4 30]]


In [43]:
mat_operations(Sample4B / 2)

[[4.5 2.  1.  4. ]
 [1.  3.  1.5 3.5]
 [2.5 0.5 0.  1.5]]


# V. Conclusion

I found this laboratory very challenging.

The task for identifying the type of matrix had taken me far too long to complete. I didn't initially know what code to use for the ones and zeros until I stumbled upon np.all() function. It checks all elements in a matrix to be true or false, and I thought that this will give me my expected results as ones and zeros only have one digit in the matrix, which I did put up as an argument in the function. For the identity, It took me a lot of trials and errors. I can not use np.all() function as there are two digits involved now and they are placed specifically: the ones in diagonal and the zeros around it. I also can not use if statements as it can be too complicated stating conditions, especially if the number of rows and columns would not be specifically determined beforehand. I wouldn't deny searching for the code just to make it work, as my knowledge about Python isn't that deep yet.

For the 2nd task, I learned that if a number is added/subtracted/multiplied/divided to a matrix, the operation will be performed regardless of the shape of the matrix. However, if two matrices are to be performed in an element-wise operations, they need to have the same shape. The element-wise multiplication is different from the matrix operation where the latter follows $m$ x $n$ and $n$ x $p$ rule to be viable for operation. However, in element-wise operations, the codes would be executed unsuccessuly if the matrices have different shapes. Because of this, I was not able to print my own message as it didn't run in the first place. I have also tried try-except code to catch the error but since it requires a bit more advance skill than I have, I wasn't able to make it work.

Matrices are important in today's technology because they may represent data and mathematical problems. They're a quick technique to get approximations for more intricate calculations. Matrices are used in any big data work as a lot of the data input to a problem comes from a single vector describing a single datum, or a group of vectors associating several data points. Many classification and clustering methods require a matrix to represent the given data as an input. Additionally, a digital image is basically a matrix so matrix multiplication is very useful in graphics: The matrix's rows and columns correspond to the rows and columns of pixels, and the numerical entries correspond to the color values of the pixels.

# VI. References


[1] Karlijn Willems, “(Tutorial) Python NUMPY Array TUTORIAL,” DataCamp Community, 2019. https://www.datacamp.com/community/tutorials/python-numpy-tutorial?utm_source=adwords_ppc&utm_campaignid=1455363063&utm_adgroupid=65083631748&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=278443377095&utm_targetid=dsa-473406585115&utm_loc_interest_ms=&utm_loc_physical_ms=9060947&gclid=CjwKCAjwhaaKBhBcEiwA8acsHJPJtZaMS_HwDDJYu9LgvPjoBk0WLmyhzBphuZhsPuFMlbS_vK_dABoCgZMQAvD_BwE#a
‌
[2] “Pyplot tutorial — Matplotlib 3.4.3 documentation,” Matplotlib.org, 2012. https://matplotlib.org/stable/tutorials/introductory/pyplot.html

[3] “SciPy - Linalg,” Tutorialspoint.com, 2021. https://www.tutorialspoint.com/scipy/scipy_linalg.htm

[4] “Introduction to Matrices | Boundless Algebra,” Lumenlearning.com, 2013. https://courses.lumenlearning.com/boundless-algebra/chapter/introduction-to-matrices/

[5] Admin, “Algebra of Matrices - Addition, Multiplication, Rules and Examples,” BYJUS, Jan. 29, 2018. https://byjus.com/maths/algebra-of-matrices/
‌
‌
